//videogames
export const GET_VIDEOGAMES = "GET_VIDEOGAMES"
export const GET_VIDEOGAMES_NAME = "GET_VIDEOGAMES_NAME"
export const GET_VIDEOGAMES_ID = "GET_VIDEOGAMES_ID"
export const CREATE_VIDEOGAME = "CREATE_VIDEOGAME"
export const FILTER_VIDEOGAME_GENRE = "FILTER_VIDEOGAME_GENRES"
export const FILTER_VIDEOGAME_PLATFORM = "FILTER_VIDEOGAME_PLATFORM"
export const DELETE_VIDEOGAME_SUCESS = "DELETE_VIDEOGAME_SUCESS"
export const PUT_VIDEOGAME = "PUT_VIDEOGAME"

//Genres
export const GET_GENRES = "GET_GENRES"

//Platforms
export const GET_PLATFORMS = "GET_PLATFORMs"

//users
export const GET_USER = "GET_USER"

//Developers

//Tags